export enum ACCOUNT_TYPE {
    STUDENT = "STUDENT",
    EMPLOYER = "EMPLOYER"
}

export enum ACCOUNT_STATUS{
    APPROVAL_PANDDING = "APPROVAL_PANDDING",
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    BLOCKED = "BLOCKED",
    DELETED = "DELETED"
}